version: '3'
services:
  airflow:
    image: apache/airflow:2.7.3
    container_name: airflow-airflow-1

    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/project
    volumes:
      - C:/GPP_TASKS1/data-orchestration-comparison:/opt/project
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: airflow standalone
